import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localeFont from "next/font/local";
import "./globals.css";
import "./styles/utilities.css";
import { Footer, Header } from "@/components/shared";
import ThemeProviders from "@/providers/ThemeProviders";
import StoreProvider from "./StoreProvider";
export const metadata: Metadata = {
  title: "motion study",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  weight: ["400", "500"],
  subsets: ["latin"],
});

const gilroyRegular = localeFont({
  src: [
    {
      path: "../../public/fonts/gilroy/Gilroy-Regular.ttf",
    },
  ],
  variable: "--font-gilroy-regular",
});
const gilroyMedium = localeFont({
  src: [
    {
      path: "../../public/fonts/gilroy/Gilroy-Medium.ttf",
    },
  ],
  variable: "--font-gilroy-medium",
});
const gilroyBold = localeFont({
  src: [
    {
      path: "../../public/fonts/gilroy/Gilroy-SemiBold.ttf",
    },
  ],
  variable: "--font-gilroy-bold",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat.className} ${gilroyRegular.variable} ${gilroyMedium.variable} ${gilroyBold.variable}`}
      >
        <StoreProvider>
          <ThemeProviders>
            <div className="min-h-screen bg-white dark:bg-slate-900 flex flex-col overflow-clip">
              <Header />
              <main>{children}</main>
              <Footer />
            </div>
          </ThemeProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
